# Generated by Django 6.0.5 on 2026-06-09 06:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scrape_jobs', '0003_jobtitle_skillalias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='desired_job_category',
        ),
        migrations.CreateModel(
            name='StudentTargetJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeting_students', to='scrape_jobs.jobtitle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_jobs', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'job_title')},
            },
        ),
    ]
