# Generated by Django 6.0.5 on 2026-08-19 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_target_occupation'),
        ('scrape_jobs', '0007_icttrack_ictrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_percentage', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('priority_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('identified_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('closed_time', models.DateTimeField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='scrape_jobs.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='accounts.student')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='accounts.studenttargetjob')),
            ],
            options={
                'ordering': ['status', '-demand_percentage', 'skill__skill_name'],
                'unique_together': {('student', 'skill', 'target')},
            },
        ),
    ]
