# Generated by Django 6.0.5 on 2026-08-24 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_skillgap'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matric_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='PrivacyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CERTIFICATE_UPLOADED', 'Certificate uploaded'), ('CERTIFICATE_VIEWED_BY_ADMIN', 'Certificate viewed by admin'), ('CERTIFICATE_VERIFIED', 'Certificate verified'), ('CERTIFICATE_REJECTED', 'Certificate rejected'), ('CERTIFICATE_DELETED', 'Certificate deleted'), ('CONSENT_ACCEPTED', 'Consent accepted'), ('CONSENT_WITHDRAWN', 'Consent withdrawn')], max_length=40)),
                ('resource_type', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('CONSENT', 'Consent')], default='CERTIFICATE', max_length=20)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_user', '-timestamp'], name='audit_target_recent'), models.Index(fields=['resource_type', 'resource_id'], name='audit_resource')],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('PRIVACY_NOTICE_ACKNOWLEDGEMENT', 'Privacy notice acknowledgement'), ('DOCUMENT_VERIFICATION_CONSENT', 'Document verification consent')], max_length=40)),
                ('notice_version', models.CharField(max_length=20)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('SIGNUP', 'Signup'), ('CERTIFICATE_UPLOAD', 'Certificate upload'), ('BACKFILL_PRE_NOTICE', 'Backfilled (pre-notice account)')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'consent_type', '-created_at'], name='consent_user_type_recent')],
            },
        ),
    ]
