# Generated by Django 6.0.5 on 2026-08-30 06:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_privacyauditlog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTargetRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200)),
                ('added_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_roles', to='accounts.student')),
            ],
            options={
                'ordering': ['added_time', 'id'],
                'unique_together': {('student', 'role_name')},
            },
        ),
        migrations.AlterField(
            model_name='skillgap',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='accounts.studenttargetrole'),
        ),
        migrations.DeleteModel(
            name='StudentTargetJob',
        ),
    ]
