# Generated by Django 6.0.5 on 2026-08-30 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studenttargetrole_alter_skillgap_target_and_more'),
        ('scrape_jobs', '0009_jobtitle_ict_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTerminologyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_text', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('context_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminology_feedback', to='scrape_jobs.icttrack')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_terminology_feedback', to='accounts.student')),
            ],
            options={
                'verbose_name_plural': 'Role terminology feedback',
                'ordering': ['-created_time'],
            },
        ),
    ]
