# Generated by Django 6.0.5 on 2026-08-30 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_roleterminologyfeedback'),
        ('scrape_jobs', '0009_jobtitle_ict_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttargetrole',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeting_students', to='scrape_jobs.icttrack'),
        ),
    ]
