# Generated by Django 6.0.5 on 2026-08-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_studenttargetrole_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacyauditlog',
            name='action',
            field=models.CharField(choices=[('CERTIFICATE_UPLOADED', 'Certificate uploaded'), ('CERTIFICATE_VIEWED_BY_ADMIN', 'Certificate viewed by admin'), ('CERTIFICATE_VERIFIED', 'Certificate verified'), ('CERTIFICATE_REJECTED', 'Certificate rejected'), ('CERTIFICATE_DELETED', 'Certificate deleted'), ('TRANSCRIPT_UPLOADED', 'Transcript uploaded'), ('TRANSCRIPT_VIEWED_BY_ADMIN', 'Transcript viewed by admin'), ('TRANSCRIPT_VERIFIED', 'Transcript verified'), ('TRANSCRIPT_REJECTED', 'Transcript rejected'), ('CONSENT_ACCEPTED', 'Consent accepted'), ('CONSENT_WITHDRAWN', 'Consent withdrawn')], max_length=40),
        ),
    ]
