# Generated by Django 6.0.5 on 2026-08-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_privacyauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsent',
            name='consent_type',
            field=models.CharField(choices=[('PRIVACY_NOTICE_ACKNOWLEDGEMENT', 'Privacy notice acknowledgement'), ('DOCUMENT_VERIFICATION_CONSENT', 'Document verification consent'), ('CV_PROCESSING_CONSENT', 'CV processing consent'), ('APPLICATION_DISCLOSURE_ACKNOWLEDGEMENT', 'Application disclosure acknowledgement')], max_length=40),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='source',
            field=models.CharField(choices=[('SIGNUP', 'Signup'), ('CERTIFICATE_UPLOAD', 'Certificate upload'), ('TRANSCRIPT_UPLOAD', 'Transcript upload'), ('CV_PARSE', 'CV parsing'), ('JOB_APPLICATION', 'Job application'), ('BACKFILL_PRE_NOTICE', 'Backfilled (pre-notice account)')], max_length=30),
        ),
    ]
