# Generated by Django 6.0.5 on 2026-08-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userconsent_consent_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studenttargetoccupation',
            name='unique_student_target_occupation',
        ),
        migrations.DeleteModel(
            name='StudentTargetOccupation',
        ),
    ]
