# Generated by Django 6.0.5 on 2026-09-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_roleterminologyfeedback_context_track_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsent',
            name='source',
            field=models.CharField(choices=[('SIGNUP', 'Signup'), ('CERTIFICATE_UPLOAD', 'Certificate upload'), ('TRANSCRIPT_UPLOAD', 'Transcript upload'), ('CV_PARSE', 'CV parsing'), ('JOB_APPLICATION', 'Job application'), ('BACKFILL_PRE_NOTICE', 'Backfilled (pre-notice account)'), ('SETTINGS_RESTORE', 'Restored in settings')], max_length=30),
        ),
    ]
