"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from dotenv import load_dotenv
import os
import sys

from django.core.exceptions import ImproperlyConfigured
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def load_env_file(path):
    if not path.exists():
        return

    for line in path.read_text().splitlines():
        line = line.strip()

        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from .env, which is gitignored. The fallback keeps a fresh clone
# running for development only -- it is prefixed django-insecure- so Django's
# own deployment check flags it if it ever reaches production.
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-local-development-only-do-not-use-in-production",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"

# The test runner forces DEBUG=False, so anything keyed on DEBUG alone would
# hand the suite its production configuration. Defined here because CACHES
# below needs it; the throttle rates further down reuse it.
_RUNNING_TESTS = "test" in sys.argv

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'accounts',
    'scrape_jobs',
    'resources',
    'dashboard',
    'job_listings',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serves STATIC_ROOT when DEBUG is false; a no-op in development, where
    # Django's own static handler is already doing it.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Credentials come from .env, which is gitignored. They were previously
# literals here, and config/settings.py is a tracked file.
# The database is PostgreSQL wherever it runs; in production it is a hosted one
# (Neon) reached across the public internet, which changes two things.
#
# TLS is required rather than preferred. sslmode defaults to "require" when
# DEBUG is false and to libpq's own default locally, so a development clone
# against a local server needs no certificates and a deployment cannot silently
# send credentials in clear. DB_SSLMODE overrides it either way.
#
# And the connection is worth keeping. Every request opening a new TLS
# connection to another host is a round trip the local socket never paid, so
# CONN_MAX_AGE holds it open; CONN_HEALTH_CHECKS is what makes that safe, since
# a pooled connection the server has since closed would otherwise surface as a
# failed request rather than a reconnect.
_SSLMODE = os.getenv("DB_SSLMODE", "" if DEBUG else "require").strip()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'momentumquest_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': int(os.getenv("DB_CONN_MAX_AGE", "0" if DEBUG else "600")),
        'CONN_HEALTH_CHECKS': not DEBUG,
        'OPTIONS': {**({"sslmode": _SSLMODE} if _SSLMODE else {})},
    }
}

# Connection reuse and the test runner do not mix: tests drop and recreate the
# database, and a held-open connection to a database being dropped blocks the
# drop. Django's own runner sets CONN_MAX_AGE to 0 for this reason; being
# explicit costs a line and saves a confusing hang.
if _RUNNING_TESTS:
    DATABASES['default']['CONN_MAX_AGE'] = 0
    DATABASES['default']['CONN_HEALTH_CHECKS'] = False


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_TZ = True

#For JWT Authentication

# The cache is shared state, not a speed-up. Throttle history lives here, so
# with Django's default per-process LocMemCache every worker keeps its own
# counters and the effective rate limit is the configured rate times the worker
# count -- which is why this is configured rather than left to the default.
#
# Three cases, chosen by DJANGO_CACHE_URL:
#
#   redis://host:6379/0   a shared cache for more than one host or worker
#   unset, DEBUG=false    the database, so a single-host deployment is correct
#                         without running another service. Needs
#                         "manage.py createcachetable" once; it is idempotent.
#   unset, DEBUG=true     in-memory, so a local clone needs nothing installed
#
# The database backend is the deliberate default for production: it is slower
# than Redis and it is *correct* across workers, and a throttle that under-
# counts is a security property quietly lost, whereas a slow cache is visible.
_CACHE_URL = os.getenv("DJANGO_CACHE_URL", "").strip()

if _CACHE_URL.startswith(("redis://", "rediss://", "unix://")):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _CACHE_URL,
            # A shared Redis can outlive a deploy and can be shared with other
            # projects; the prefix keeps this application's keys its own.
            "KEY_PREFIX": os.getenv("DJANGO_CACHE_PREFIX", "momentumquest"),
        }
    }
elif DEBUG or _RUNNING_TESTS:
    # The test runner lands here too, deliberately. It forces DEBUG=False, and
    # the database backend needs a table that createcachetable makes rather
    # than a migration -- so the suite would fail on the first throttled
    # request, in a configuration no deployment runs.
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "momentumquest-dev",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": os.getenv("DJANGO_CACHE_TABLE", "django_cache"),
            "KEY_PREFIX": os.getenv("DJANGO_CACHE_PREFIX", "momentumquest"),
        }
    }


# Throttling is scoped rather than global: the public job feed is meant to be
# browsed freely, while the endpoints that send mail, mint tokens or accept a
# guessable token are the ones worth rate-limiting. Each rate is overridable by
# environment variable so a deployment can tighten one without a code change.
#
# Counted per client IP for anonymous callers, which is what these endpoints
# see. The history lives in Django's cache, which CACHES above points at shared
# storage whenever DEBUG is false -- without that, each worker counts alone and
# the effective limit is the rate times the worker count.
_THROTTLE_RATES = {
    # Credential stuffing is the thing being slowed here, so this is the
    # tightest of the set and is measured per minute.
    "login": os.getenv("THROTTLE_LOGIN", "10/min"),
    "register": os.getenv("THROTTLE_REGISTER", "10/hour"),
    "verify_email": os.getenv("THROTTLE_VERIFY_EMAIL", "20/hour"),
    # Sends mail to an address the caller names, so an unlimited version is an
    # open relay for harassment as much as an account risk.
    "password_reset": os.getenv("THROTTLE_PASSWORD_RESET", "5/hour"),
    # The confirm endpoints take a token from a link. They are the ones a
    # brute-force actually targets, so they are throttled at least as hard as
    # the request that issues the token.
    "token_confirm": os.getenv("THROTTLE_TOKEN_CONFIRM", "10/hour"),
}

# Relaxed under the test runner, not removed. Throttle history is keyed by
# scope and client IP, and every test shares 127.0.0.1, so the real rates would
# accumulate across the whole suite and fail unrelated tests by exhaustion
# rather than by defect.
#
# The rates are raised rather than the scopes dropped, because dropping them
# does not disable throttling -- ScopedRateThrottle.get_rate() raises
# ImproperlyConfigured for a scope it cannot find a rate for, so an empty dict
# turns every throttled endpoint into a 500. It also keeps the throttle code
# path executing in every test instead of being skipped in exactly the
# configuration nobody runs in production.
#
# The limits themselves are exercised deliberately by AuthThrottleTests, which
# patches these rates down to numbers a test can reach.
_TEST_RATE = "100000/min"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': (
        {scope: _TEST_RATE for scope in _THROTTLE_RATES}
        if _RUNNING_TESTS else _THROTTLE_RATES
    ),
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# collectstatic needs a destination. Without it the command raises and any
# deployment that serves static assets from the web server cannot be built.
# Gitignored: it is a build artefact, regenerated by collectstatic.
STATIC_ROOT = Path(os.getenv("DJANGO_STATIC_ROOT", BASE_DIR / 'staticfiles'))
MEDIA_URL  = '/media/'
MEDIA_ROOT = Path(os.getenv("DJANGO_MEDIA_ROOT", BASE_DIR / 'media'))

# Django serves its own admin CSS and JS only while DEBUG is true. Behind
# waitress with DEBUG=false the admin renders as unstyled HTML unless
# something serves STATIC_ROOT -- so WhiteNoise does it from the app itself,
# which is one fewer moving part than a separate static server for a handful
# of admin assets.
#
# Placed directly after SecurityMiddleware, which is where its documentation
# requires it: before everything that might short-circuit a response.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ============================================================
# Production hardening
#
# Every setting below is a no-op in development (DEBUG=true) and takes effect
# only when DEBUG is false, so a local clone keeps working unchanged while a
# deployment gets the protections `manage.py check --deploy` asks for.
# ============================================================

if not DEBUG:
    # A deployment must supply its own key. Failing loudly at startup is far
    # better than silently signing sessions with a value that is in the repo.
    if SECRET_KEY.startswith("django-insecure-"):
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set to a real secret when DEBUG is false. "
            "Generate one with: python -c "
            "\"from django.core.management.utils import get_random_secret_key as k; print(k())\""
        )

    SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "true").lower() == "true"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Six months. Start lower (e.g. 3600) when first enabling HTTPS, because a
    # browser honours the longest value it has seen and a mistake is not
    # quickly undone.
    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_HSTS_SECONDS", 60 * 60 * 24 * 180))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # Behind a TLS-terminating proxy Django sees plain HTTP and would redirect
    # forever. Set this only when such a proxy is actually in front.
    if os.getenv("DJANGO_BEHIND_TLS_PROXY", "false").lower() == "true":
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Certificates carry the student's full name and often an identification
# number, so they are stored OUTSIDE MEDIA_ROOT -- the static() helper in
# config/urls.py serves everything under MEDIA_ROOT with no authentication.
# They are read back only through CertificateFileView, which checks ownership.
#
# Configurable because the default sits inside the checkout, which is the
# wrong place for anything that must survive a redeploy. In production the
# filesystem is not used at all -- see PRIVATE_STORAGE_BACKEND below.
#
# Transcripts are not stored at all -- the upload reads the subjects and
# deletes the PDF before it responds -- so only certificates live here.
PRIVATE_MEDIA_ROOT = Path(
    os.getenv("DJANGO_PRIVATE_MEDIA_ROOT", BASE_DIR / 'private_media'))

# Where private documents actually live.
#
#   filesystem   PRIVATE_MEDIA_ROOT above. Development, and any deployment with
#                genuinely durable local storage.
#   r2           a private Cloudflare R2 bucket over the S3 API. Production.
#
# Left unset, the R2 variables decide: configured means R2, absent means the
# filesystem *only while DEBUG is true*. With DEBUG false and no bucket,
# resources.private_storage refuses to start -- deliberately. Free hosting gives
# a container ephemeral storage, so a filesystem-backed certificate is discarded
# by the next deploy: the upload succeeds, the row is written, the student is
# told it worked, and months later the file is gone with nothing in any log.
# There is no error to catch, so the only place to fail is startup.
#
# PRIVATE_STORAGE_ALLOW_LOCAL is the deliberate override for a deployment whose
# local disk really does persist.
PRIVATE_STORAGE_BACKEND = os.getenv("PRIVATE_STORAGE_BACKEND", "").strip()
#
# True under the test runner, which forces DEBUG=False: the suite has no bucket
# and wants none, and every document test writes to a temporary directory. The
# same reason CACHES treats the runner separately.
PRIVATE_STORAGE_ALLOW_LOCAL = (
    os.getenv("PRIVATE_STORAGE_ALLOW_LOCAL", "false").lower() == "true"
    or _RUNNING_TESTS)

# The bucket is private: no public access, no permanent object URLs. Every read
# goes back through the view that checked ownership, so there is exactly one
# rule and no second route to the bytes.
R2_SETTINGS = {
    "bucket":       os.getenv("R2_BUCKET", "").strip(),
    "endpoint_url": os.getenv("R2_ENDPOINT_URL", "").strip(),
    "access_key":   os.getenv("R2_ACCESS_KEY_ID", "").strip(),
    "secret_key":   os.getenv("R2_SECRET_ACCESS_KEY", "").strip(),
    # R2 ignores the region but the S3 client requires one.
    "region":       os.getenv("R2_REGION", "auto").strip(),
}

AUTH_USER_MODEL = 'accounts.User'

# Read from the environment like ALLOWED_HOSTS and FRONTEND_URL. The default
# is the local dev pair, so a fresh clone still works without a .env; a
# deployment sets CORS_ALLOWED_ORIGINS rather than editing this file.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000",
    ).split(",")
    if origin.strip()
]

# CSRF's companion to the list above, and a separate setting because it answers
# a different question: CORS decides who may *read* a response, CSRF_TRUSTED_-
# ORIGINS decides whose form posts and unsafe methods are believed. Django
# compares the Origin header against this list for every unsafe request over
# HTTPS, so the admin behind a TLS proxy needs its own origin here even though
# no cross-site call is involved.
#
# Defaults to the CORS list rather than to empty: an origin already trusted to
# make credentialed cross-origin requests is one whose posts are trusted too,
# and an empty default fails closed at the first admin login on staging with a
# message that does not name this setting. Entries must carry the scheme.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS", ",".join(CORS_ALLOWED_ORIGINS)
    ).split(",")
    if origin.strip()
]

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
)

# Read by config.email.ResendEmailBackend when EMAIL_BACKEND points at it.
# Production sends over HTTPS rather than SMTP: free hosting commonly blocks
# outbound SMTP ports, and a blocked port means send_mail hangs, the
# registration request still succeeds, and the verification link never arrives.
EMAIL_API_KEY = os.getenv("EMAIL_API_KEY", "").strip()

# Gmail API over HTTPS, the production transport. Gmail speaks SMTP too, and
# that is the wrong choice here: outbound SMTP ports are commonly blocked on
# free hosting, and the failure is silent -- send_mail waits for a connection
# that never opens while the registration request still returns success.
#
# Refresh-token OAuth. The refresh token is exchanged for a short-lived access
# token per batch, and that access token is never persisted -- see
# config/email.py. The OAuth client is scoped to gmail.send alone: no inbox
# read, no mailbox modification.
#
# The sender is DEFAULT_FROM_EMAIL and nothing else. There is deliberately no
# GMAIL_SENDER_EMAIL: Gmail sends as the account the refresh token belongs to,
# so a second sender variable could disagree with reality while looking
# authoritative -- misleading configuration is worse than none.
#
# DEFAULT_FROM_EMAIL should normally name that same account. Gmail rewrites the
# From header to the authenticated account unless the address is a verified
# "Send mail as" alias on it, so a different address there is silently replaced
# rather than honoured.
GMAIL_CLIENT_ID = os.getenv("GMAIL_CLIENT_ID", "").strip()
GMAIL_CLIENT_SECRET = os.getenv("GMAIL_CLIENT_SECRET", "").strip()
GMAIL_REFRESH_TOKEN = os.getenv("GMAIL_REFRESH_TOKEN", "").strip()

EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

# The fallback interpolates EMAIL_HOST_USER, which is os.getenv with no default
# -- so with no SMTP user configured this becomes the literal string
# "MomentumQuest <None>". Harmless with the console or locmem backend, and a
# rejected or misattributed message in production, which is why
# GmailApiEmailBackend refuses to start on an address it cannot use.
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    f"MomentumQuest <{EMAIL_HOST_USER}>"
)
VERIFICATION_TIMEOUT = int(os.getenv("VERIFICATION_TIMEOUT", 60 * 15))

# Published in the privacy notice as the address students write to about their
# personal data. Injected at read time rather than baked into the notice text,
# so changing it does not require publishing a new notice version.
PRIVACY_CONTACT_EMAIL = os.getenv(
    "PRIVACY_CONTACT_EMAIL",
    EMAIL_HOST_USER or "privacy@momentumquest.local"
)

# Unhandled exceptions must reach the deployment's logs.
#
# Without this, a production 500 left no trace at all: Render showed gunicorn's
# access line and nothing else. Django does log the exception, with its
# traceback, through django.request -- but with no LOGGING configured, Django's
# defaults send it to two handlers that both discard it when DEBUG is false:
#
#   console      filtered by require_debug_true, so silent in production;
#   mail_admins  sends to ADMINS, and none are configured.
#
# The record would then propagate to the root logger, which gunicorn never gives
# a handler (it configures only gunicorn.error and gunicorn.access). And because
# handlers *were* found on the way, Python's last-resort stderr handler does not
# engage either. Waitress does call logging.basicConfig(), which is why the same
# failure printed a traceback locally and nothing on Render.
#
# So django.request gets its own stderr handler, independent of DEBUG. It does
# not propagate, so development does not print each error twice.
#
# What reaches the logs is redacted. The request body is never rendered -- a
# format string does not print the request django.request attaches -- but
# exception messages can carry values from the failing statement, and User.email
# is unique, so a duplicate-address error would print the address.
# RedactingFormatter strips email addresses and tokens from the fully formatted
# record, traceback included. The HTTP response is unaffected: with DEBUG false
# the client still receives Django's generic 500 page and no exception detail.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "redacted": {
            "()": "config.log_redaction.RedactingFormatter",
            "format": "%(asctime)s %(levelname)s %(name)s: %(message)s",
        },
    },
    "handlers": {
        "stderr": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stderr",
            "formatter": "redacted",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["stderr"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
