# Generated by Django 6.0.5 on 2026-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('EVERYONE', 'Everyone'), ('STUDENTS', 'Students Only'), ('COMPANIES', 'Companies Only')], default='EVERYONE', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='supporting_doc',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
