# Generated by Django 6.0.5 on 2026-06-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_announcement_audience_announcement_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='supporting_doc',
            field=models.URLField(blank=True, null=True),
        ),
    ]
