# Generated by Django 6.0.5 on 2026-05-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('BLOCKED', 'Blocked by Anti-Bot'), ('PARTIAL', 'Partial (some pages blocked)'), ('FAILED', 'Failed')], default='FAILED', max_length=20)),
                ('roles_scraped', models.JSONField(default=list)),
                ('pages_attempted', models.IntegerField(default=0)),
                ('jobs_scraped', models.IntegerField(default=0)),
                ('jobs_created', models.IntegerField(default=0)),
                ('jobs_updated', models.IntegerField(default=0)),
                ('blocked_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='scrapedjob',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scrapedjob',
            name='job_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scrapedjob',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scrapedjob',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedjob',
            name='salary_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
