# Generated by Django 6.0.5 on 2026-05-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_scrapedjob_add_fields_scrapelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('type', models.CharField(max_length=100)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='jobs.skill')),
            ],
            options={
                'ordering': ['platform', 'title'],
                'unique_together': {('skill', 'url')},
            },
        ),
    ]
