# Generated by Django 6.0.5 on 2026-05-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_learning_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
