# Generated by Django 6.0.5 on 2026-05-26 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_learning_resource_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_learning_resources', to='jobs.skill'),
        ),
    ]
