/**
 * The full MomentumQuest privacy notice, at the URL given to Google as the
 * application's privacy policy.
 *
 * A server component, so the notice is in the HTML the server sends rather than
 * arriving later from JavaScript. That matters for two readers the previous,
 * fully client-side page failed: a reviewer or crawler with scripts disabled saw
 * only a heading, and anyone arriving while the free API instance was asleep saw
 * a loading placeholder and then, often, "could not be loaded".
 *
 * The text comes from a snapshot generated by the backend
 * (`python manage.py export_privacy_notice`), because Vercel builds this
 * directory alone and cannot import accounts.privacy_notice. It is not a second
 * privacy policy: the backend suite fails if the snapshot differs from the
 * canonical notice, and the page still upgrades to the live API response once it
 * loads -- see PrivacyNoticeView.
 *
 * Deliberately a top-level route outside every route group, and outside
 * DashboardLayout: acknowledging this notice is a precondition of creating an
 * account, so it has to be readable by someone who does not have one.
 */

import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { Logo } from '@/src/components/Logo';
import { PrivacyNoticeView } from '@/src/components/PrivacyNoticeView';
import type { PrivacyNotice } from '@/src/lib/privacyNotice';
import snapshot from '@/src/lib/privacyNoticeSnapshot.json';

const publishedNotice = snapshot.notice as PrivacyNotice;

export const metadata: Metadata = {
  title: `Privacy Notice | MomentumQuest`,
  description:
    `How MomentumQuest collects, uses, stores and protects personal data. ` +
    `Version ${publishedNotice.version}, effective ${publishedNotice.effective_date}.`,
};

export default function PrivacyNoticePage() {
  return (
    <div className="min-h-screen bg-neutral-50">
      <header className="border-b border-neutral-200 bg-white">
        <div className="mx-auto flex max-w-3xl items-center justify-between gap-4 px-6 py-4">
          <Logo size="sm" />
          <Link
            href="/signup"
            className="flex items-center gap-1.5 text-sm font-semibold text-primary hover:underline"
          >
            <ArrowLeft size={16} /> Back to sign up
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-10">
        <PrivacyNoticeView initialNotice={publishedNotice} />
      </main>
    </div>
  );
}
