# Generated by Django 6.0.5 on 2026-05-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Job categories',
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('BLOCKED', 'Blocked by Anti-Bot'), ('PARTIAL', 'Partial (some pages blocked)'), ('FAILED', 'Failed')], default='FAILED', max_length=20)),
                ('roles_scraped', models.JSONField(default=list)),
                ('pages_attempted', models.IntegerField(default=0)),
                ('jobs_scraped', models.IntegerField(default=0)),
                ('jobs_created', models.IntegerField(default=0)),
                ('jobs_updated', models.IntegerField(default=0)),
                ('blocked_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('skill_category', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('salary_text', models.CharField(blank=True, max_length=100)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('source_portal', models.CharField(default='JobStreet', max_length=100)),
                ('source_url', models.URLField(unique=True)),
                ('scraped_time', models.DateTimeField(auto_now=True)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_jobs', to='scrape_jobs.jobcategory')),
            ],
            options={
                'ordering': ['-scraped_time'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedJobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_method', models.CharField(default='keyword', max_length=50)),
                ('scraped_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_job_skills', to='scrape_jobs.scrapedjob')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_job_skills', to='scrape_jobs.skill')),
            ],
            options={
                'unique_together': {('scraped_job', 'skill')},
            },
        ),
    ]
