# Generated by Django 6.0.5 on 2026-06-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0001_initial'),
        # Must run AFTER scraped rows are copied into JobListing, otherwise a
        # fresh-DB migrate would delete the source data before the copy.
        ('job_listings', '0003_migrate_scraped_jobs'),
    ]

    operations = [
        # Clear the composite unique constraint BEFORE removing its fields.
        migrations.AlterUniqueTogether(
            name='scrapedjobskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scrapedjobskill',
            name='scraped_job',
        ),
        migrations.RemoveField(
            model_name='scrapedjobskill',
            name='skill',
        ),
        migrations.DeleteModel(
            name='ScrapedJob',
        ),
        migrations.DeleteModel(
            name='ScrapedJobSkill',
        ),
    ]
