# Generated by Django 6.0.5 on 2026-06-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0002_remove_scrapedjobskill_scraped_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles', to='scrape_jobs.jobcategory')),
            ],
            options={
                'ordering': ['title_name'],
            },
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=100, unique=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='scrape_jobs.skill')),
            ],
            options={
                'verbose_name_plural': 'Skill aliases',
                'ordering': ['alias_name'],
            },
        ),
    ]
