# Generated by Django 6.0.5 on 2026-08-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0006_occupation_taxonomies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICTTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('is_fallback', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ICTRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy_id', models.CharField(max_length=255, unique=True)),
                ('subtrack', models.CharField(max_length=150)),
                ('role_name', models.CharField(max_length=200)),
                ('normalized_role', models.CharField(db_index=True, max_length=200)),
                ('career_level', models.CharField(choices=[('ASSOCIATE', 'Associate'), ('PROFESSIONAL', 'Professional'), ('SENIOR', 'Senior'), ('LEAD', 'Lead'), ('ARCHITECT', 'Architect'), ('MANAGER', 'Manager'), ('DIRECTOR', 'Director'), ('HEAD', 'Head'), ('EXECUTIVE', 'Executive')], max_length=20)),
                ('progression_order', models.IntegerField(default=0)),
                ('is_cross_subtrack', models.BooleanField(default=False)),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('version', models.CharField(blank=True, max_length=30)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='scrape_jobs.icttrack')),
            ],
            options={
                'ordering': ['track__display_order', 'subtrack', 'progression_order', 'role_name'],
            },
        ),
    ]
