# Generated by Django 6.0.5 on 2026-08-19 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0007_icttrack_ictrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICTRoleOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('EXACT', 'Exact'), ('CLOSE', 'Close'), ('BROAD', 'MASCO concept is broader')], default='CLOSE', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('occupation', models.ForeignKey(limit_choices_to={'taxonomy': 'MASCO'}, on_delete=django.db.models.deletion.CASCADE, related_name='ict_role_links', to='scrape_jobs.occupationconcept')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_links', to='scrape_jobs.ictrole')),
            ],
            options={
                'ordering': ['role__track__display_order', 'role__role_name'],
                'unique_together': {('role', 'occupation')},
            },
        ),
    ]
