# Generated by Django 6.0.5 on 2026-08-23 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0008_ictroleoccupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='ict_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles', to='scrape_jobs.icttrack'),
        ),
    ]
