# Generated by Django 6.0.5 on 2026-08-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_studenttargetoccupation_unique_student_target_occupation_and_more'),
        ('job_listings', '0015_rename_occupation_seniority_joblisting_seniority_and_more'),
        ('scrape_jobs', '0009_jobtitle_ict_track'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ictroleoccupation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ictroleoccupation',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='ictroleoccupation',
            name='role',
        ),
        migrations.RemoveConstraint(
            model_name='occupationconcept',
            name='unique_occupation_concept_version',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='canonical_occupation',
        ),
        migrations.RemoveConstraint(
            model_name='occupationmapping',
            name='unique_masco_esco_mapping',
        ),
        migrations.RemoveConstraint(
            model_name='occupationmapping',
            name='occupation_mapping_confidence_range',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='occupation_match_confidence',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='occupation_match_method',
        ),
        migrations.DeleteModel(
            name='ICTRoleOccupation',
        ),
        migrations.RemoveField(
            model_name='occupationmapping',
            name='esco',
        ),
        migrations.RemoveField(
            model_name='occupationmapping',
            name='masco',
        ),
        migrations.DeleteModel(
            name='OccupationConcept',
        ),
        migrations.DeleteModel(
            name='OccupationMapping',
        ),
    ]
