# Generated by Django 6.0.5 on 2026-08-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0010_alter_ictroleoccupation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICTRoleAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=200, unique=True)),
                ('role_name', models.CharField(db_index=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ICT role aliases',
                'ordering': ['alias_name'],
            },
        ),
    ]
