# Generated by Django 6.0.5 on 2026-08-31 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0018_marketrolecandidate_and_more'),
        ('scrape_jobs', '0011_ictrolealias'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('broad_area', models.CharField(blank=True, db_index=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['broad_area', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketRoleAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_title', models.CharField(max_length=250, unique=True)),
                ('mapping_type', models.CharField(choices=[('exact', 'Normalized form of the Market Role name'), ('reviewed_alias', 'Reviewed naming variation'), ('reviewed_segment', 'Reviewed compound-title segment')], default='reviewed_alias', max_length=20)),
                ('reviewed', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('market_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='scrape_jobs.marketrole')),
            ],
            options={
                'verbose_name_plural': 'market role aliases',
                'ordering': ['normalized_title'],
            },
        ),
        migrations.RemoveField(
            model_name='ictrole',
            name='track',
        ),
        migrations.DeleteModel(
            name='ICTRoleAlias',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='ict_track',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='seniority',
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='career_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='market_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles', to='scrape_jobs.marketrole'),
        ),
        migrations.DeleteModel(
            name='ICTRole',
        ),
    ]
