# Generated by Django 6.0.5 on 2026-08-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_roleterminologyfeedback_context_track_and_more'),
        ('job_listings', '0019_joblisting_market_role_joblisting_matched_alias_and_more'),
        ('scrape_jobs', '0012_marketrole_marketrolealias_remove_ictrole_track_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ICTTrack',
        ),
    ]
