# Generated by Django 6.0.5 on 2026-09-03 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0014_seed_enterprise_skill_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='catalogue_status',
            field=models.CharField(choices=[('ACTIVE_INTERNAL', 'Curated internally'), ('MTO_EXTENSION', 'Added from the MIND Tech Ontology'), ('MARKET_EXTENSION', 'Observed in Malaysian adverts'), ('REVIEW_REQUIRED', 'Awaiting a reviewer'), ('DEPRECATED', 'Retired')], db_index=True, default='ACTIVE_INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='skill',
            name='technical_domain',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skillalias',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skillalias',
            name='requires_context',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillalias',
            name='source',
            field=models.CharField(choices=[('INTERNAL', 'Curated internally'), ('MTO', 'MIND Tech Ontology'), ('STACKOVERFLOW', 'Stack Overflow tag synonym')], default='INTERNAL', max_length=20),
        ),
        migrations.CreateModel(
            name='SkillRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('IMPLIES_KNOWING', 'Implies knowing'), ('SUPPORTED_LANGUAGE', 'Supported language'), ('RELATED_TECHNOLOGY', 'Related technology')], max_length=24)),
                ('source', models.CharField(default='MTO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_out', to='scrape_jobs.skill')),
                ('to_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_in', to='scrape_jobs.skill')),
            ],
            options={
                'ordering': ['from_skill__skill_name', 'relationship_type'],
                'unique_together': {('from_skill', 'to_skill', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='SkillSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('INTERNAL', 'Curated internally'), ('MTO', 'MIND Tech Skills & Concepts Ontology'), ('ONET', 'O*NET Software Skills'), ('LIGHTCAST', 'Lightcast Open Skills'), ('DATAMATA', 'Datamata Skill Demand Index'), ('MALAYSIA_JD', 'Observed in the Malaysian corpus')], db_index=True, max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('external_label', models.CharField(blank=True, max_length=200)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='scrape_jobs.skill')),
            ],
            options={
                'ordering': ['skill__skill_name', 'source'],
                'unique_together': {('skill', 'source', 'external_label')},
            },
        ),
    ]
