# Generated by Django 6.0.5 on 2026-09-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0016_backfill_internal_skill_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='catalogue_status',
            field=models.CharField(choices=[('ACTIVE_INTERNAL', 'Curated internally'), ('MTO_EXTENSION', 'Added from the MIND Tech Ontology'), ('MARKET_EXTENSION', 'Observed in Malaysian adverts'), ('REVIEW_REQUIRED', 'Awaiting a reviewer'), ('DEPRECATED', 'Retired')], db_default='ACTIVE_INTERNAL', db_index=True, default='ACTIVE_INTERNAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, db_default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='skill',
            name='technical_domain',
            field=models.CharField(blank=True, db_default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='skillalias',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='skillalias',
            name='requires_context',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='skillalias',
            name='source',
            field=models.CharField(choices=[('INTERNAL', 'Curated internally'), ('MTO', 'MIND Tech Ontology'), ('STACKOVERFLOW', 'Stack Overflow tag synonym')], db_default='INTERNAL', default='INTERNAL', max_length=20),
        ),
    ]
