# Generated by Django 6.0.5 on 2026-09-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0017_alter_skill_catalogue_status_alter_skill_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsource',
            name='source',
            field=models.CharField(choices=[('INTERNAL', 'Curated internally'), ('MTO', 'MIND Tech Skills & Concepts Ontology'), ('ONET', 'O*NET Software Skills'), ('LIGHTCAST', 'Lightcast Open Skills'), ('DATAMATA', 'Datamata Skill Demand Index'), ('MALAYSIA_JD', 'Observed in the Malaysian corpus'), ('TECH_JOBS', 'Tech Jobs Dataset (corroboration)'), ('QARERA_2026', 'Qarera 2026 demand index (corroboration)')], db_index=True, max_length=20),
        ),
    ]
