# Generated by Django 6.0.5 on 2026-09-03 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0020_remove_malformed_skill_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketrole',
            name='catalogue_origin',
            field=models.CharField(choices=[('MARKET_DERIVED', 'Derived from Malaysian adverts'), ('IMDA_MARKET_EXTENSION', 'IMDA role promoted on Malaysian evidence')], db_default='MARKET_DERIVED', default='MARKET_DERIVED', max_length=32),
        ),
        migrations.CreateModel(
            name='IMDARoleReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=200, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('base_role_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('seniority_level', models.CharField(blank=True, choices=[('CHIEF', 'Chief'), ('SENIOR', 'Senior'), ('ASSOCIATE', 'Associate'), ('JUNIOR', 'Junior'), ('ENTRY', 'Entry')], db_default='', max_length=12)),
                ('imda_category', models.CharField(blank=True, db_default='', max_length=120)),
                ('imda_subcategory', models.CharField(blank=True, db_default='', max_length=120)),
                ('imda_source_id', models.CharField(blank=True, db_default='', max_length=60)),
                ('malaysia_advert_count', models.PositiveIntegerField(db_default=0, default=0)),
                ('malaysia_company_count', models.PositiveIntegerField(db_default=0, default=0)),
                ('mapping_status', models.CharField(choices=[('UNMAPPED', 'Not yet examined'), ('MAPPED_EXISTING', 'Mapped to an existing Market Role'), ('PROMOTED_MARKET_ROLE', 'Promoted to a new Market Role'), ('REVIEW_REQUIRED', 'Needs a reviewer'), ('NO_MARKET_EVIDENCE', 'Official role, no Malaysian adverts')], db_default='UNMAPPED', db_index=True, default='UNMAPPED', max_length=24)),
                ('source_version', models.CharField(blank=True, db_default='', max_length=120)),
                ('source_reference', models.CharField(blank=True, db_default='', max_length=300)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imda_references', to='scrape_jobs.marketrole')),
            ],
            options={
                'verbose_name': 'IMDA role reference',
                'ordering': ['official_name'],
            },
        ),
        migrations.CreateModel(
            name='IMDARoleMarketMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(choices=[('EXACT', 'Names match exactly'), ('NORMALIZED', 'Match after normalisation'), ('SENIORITY_COLLAPSE', 'Match after removing a rank word'), ('REVIEWED_ALIAS', 'Matched a reviewed alias'), ('MARKET_PROMOTION', 'New Market Role created on Malaysian evidence')], max_length=24)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_default='PENDING', default='PENDING', max_length=10)),
                ('evidence_count', models.PositiveIntegerField(db_default=0, default=0)),
                ('evidence_company_count', models.PositiveIntegerField(db_default=0, default=0)),
                ('reviewed_by', models.CharField(blank=True, db_default='', max_length=120)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, db_default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imda_mappings', to='scrape_jobs.marketrole')),
                ('imda_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='scrape_jobs.imdarolereference')),
            ],
            options={
                'ordering': ['imda_role__official_name'],
                'unique_together': {('imda_role', 'market_role')},
            },
        ),
    ]
