# Generated by Django 6.0.5 on 2026-09-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_jobs', '0021_marketrole_catalogue_origin_imdarolereference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketrolealias',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='marketrolealias',
            name='malaysia_advert_count',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='marketrolealias',
            name='malaysia_company_count',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='marketrolealias',
            name='requires_body_context',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='marketrolealias',
            name='review_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending review'), ('REJECTED', 'Rejected')], db_default='APPROVED', default='APPROVED', max_length=10),
        ),
        migrations.AddField(
            model_name='marketrolealias',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Entered by hand'), ('IMDA', 'From the IMDA reference layer'), ('MALAYSIA_TITLE_REVIEW', 'Reviewed from Malaysian advert titles'), ('LEGACY', 'Predates alias provenance')], db_default='LEGACY', default='LEGACY', max_length=24),
        ),
        migrations.AddField(
            model_name='marketrolealias',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
