# Generated by Django 6.0.5 on 2026-06-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogramme',
            name='supporting_doc',
            field=models.URLField(blank=True, null=True),
        ),
    ]
