# Generated by Django 6.0.5 on 2026-08-18 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_target_occupation'),
        ('resources', '0002_trainingprogramme_supporting_doc'),
        ('scrape_jobs', '0006_occupation_taxonomies'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PARSED', 'Parsed'), ('FAILED', 'Failed')], default='PARSED', max_length=20)),
                ('parsed_subjects', models.JSONField(blank=True, default=list)),
                ('skills_added', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='accounts.student')),
            ],
            options={
                'ordering': ['-uploaded_time'],
            },
        ),
        migrations.CreateModel(
            name='SubjectSkillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(db_index=True, max_length=20)),
                ('subject_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='scrape_jobs.skill')),
            ],
            options={
                'ordering': ['subject_code', 'skill__skill_name'],
                'unique_together': {('subject_code', 'skill')},
            },
        ),
    ]
