# Generated by Django 6.0.5 on 2026-08-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_transcriptupload_subjectskillmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
