# Generated by Django 6.0.5 on 2026-05-27 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentskill'),
        ('jobs', '0006_remove_learning_resource'),
        ('resources', '0003_resource_scrape_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('programme_duration', models.CharField(blank=True, max_length=100)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_programmes', to='accounts.adminprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programmes', to='accounts.company')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_programmes', to='jobs.skill')),
            ],
            options={
                'ordering': ['-submission_time'],
            },
        ),
    ]
