# Generated by Django 6.0.5 on 2026-08-24 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_matric_number_privacyauditlog_userconsent'),
        ('resources', '0004_certificate_file_path_certificate_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('EXAM_RESULT', 'Examination result'), ('TRANSCRIPT', 'Transcript'), ('OTHER', 'Other supporting document')], default='CERTIFICATE', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('NAME_MISMATCH', 'Name does not match'), ('UNREADABLE_DOCUMENT', 'Document is unreadable'), ('INCORRECT_DOCUMENT', 'Incorrect document'), ('INSUFFICIENT_INFORMATION', 'Insufficient information'), ('SUSPECTED_INVALID_DOCUMENT', 'Suspected invalid document'), ('OTHER', 'Other')], max_length=40),
        ),
        migrations.AddField(
            model_name='certificate',
            name='upload_consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='accounts.userconsent'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
