# Generated by Django 6.0.5 on 2026-08-24 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_privacyauditlog_action_and_more'),
        ('resources', '0005_certificate_certificate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptupload',
            name='upload_consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcripts', to='accounts.userconsent'),
        ),
    ]
