# Generated by Django 6.0.5 on 2026-08-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_studenttargetrole_track'),
        ('resources', '0006_transcriptupload_upload_consent'),
        ('scrape_jobs', '0009_jobtitle_ict_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptupload',
            name='classification_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transcriptupload',
            name='classification_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transcriptupload',
            name='detected_institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transcriptupload',
            name='document_type_status',
            field=models.CharField(choices=[('LIKELY_TRANSCRIPT', 'Likely a transcript'), ('UNCERTAIN', 'Uncertain'), ('NOT_TRANSCRIPT', 'Not a transcript'), ('LEGACY_UNVERIFIED', 'Legacy, never verified')], default='UNCERTAIN', max_length=20),
        ),
        migrations.AddField(
            model_name='transcriptupload',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transcriptupload',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptupload',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transcripts', to='accounts.adminprofile'),
        ),
        migrations.AddField(
            model_name='transcriptupload',
            name='skills_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptupload',
            name='student_identity_matched',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptupload',
            name='verification_method',
            field=models.CharField(choices=[('NONE', 'None'), ('ADMIN_REVIEW', 'Administrator review'), ('DIGITAL_SIGNATURE', 'Digital signature'), ('QR_VERIFICATION', 'QR verification')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='transcriptupload',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Awaiting verification'), ('AUTO_VERIFIED', 'Automatically verified'), ('MANUALLY_VERIFIED', 'Verified by an administrator'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='TranscriptSkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_evidence', to='scrape_jobs.skill')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidence', to='resources.transcriptupload')),
            ],
            options={
                'verbose_name_plural': 'Transcript skill evidence',
                'ordering': ['-applied_at'],
                'unique_together': {('transcript', 'skill')},
            },
        ),
    ]
