# Generated by Django 6.0.5 on 2026-08-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_flag_legacy_transcripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptupload',
            name='verification_method',
            field=models.CharField(choices=[('NONE', 'None'), ('CLASSIFICATION', 'Automatic classification'), ('ADMIN_REVIEW', 'Administrator review'), ('DIGITAL_SIGNATURE', 'Digital signature'), ('QR_VERIFICATION', 'QR verification')], default='NONE', max_length=20),
        ),
    ]
