# Generated by Django 6.0.5 on 2026-09-01 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_sanitize_stored_html'),
        ('scrape_jobs', '0013_delete_icttrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='scrape_jobs.skill'),
        ),
        migrations.CreateModel(
            name='CertificateSkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=20)),
                ('approved_level', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidence', to='resources.certificate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_evidence', to='scrape_jobs.skill')),
            ],
            options={
                'verbose_name_plural': 'certificate skill evidence',
                'ordering': ['certificate_id', 'skill__skill_name'],
                'constraints': [models.UniqueConstraint(fields=('certificate', 'skill'), name='unique_certificate_skill_evidence')],
            },
        ),
    ]
