# Generated by Django 6.0.5 on 2026-09-03 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_delete_rejected_transcripts'),
        ('scrape_jobs', '0019_quarantine_malformed_skill_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='resources.course')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='scrape_jobs.skill')),
            ],
            options={
                'ordering': ['course_id', '-is_primary'],
                'unique_together': {('course', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='taught_by_courses', through='resources.CourseSkill', to='scrape_jobs.skill'),
        ),
        migrations.CreateModel(
            name='TrainingProgrammeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='resources.trainingprogramme')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_links', to='scrape_jobs.skill')),
            ],
            options={
                'ordering': ['programme_id', '-is_primary'],
                'unique_together': {('programme', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='trainingprogramme',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='taught_by_programmes', through='resources.TrainingProgrammeSkill', to='scrape_jobs.skill'),
        ),
    ]
