# Generated by Django 6.0.5 on 2026-09-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_populate_course_skill_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('categories', models.JSONField(default=list)),
                ('card_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['platform', 'title'],
            },
        ),
    ]
