# Generated by Django 6.0.5 on 2026-09-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_coursecatalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecatalogue',
            name='discovered_via',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
