# Generated by Django 6.0.5 on 2026-09-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_coursecatalogue_discovered_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecatalogue',
            name='is_free',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
