# Generated by Django 6.0.5 on 2026-09-10 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_coursecatalogue_is_free'),
        ('scrape_jobs', '0028_retire_geo_and_chatgpt_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedResourceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_resources', to='scrape_jobs.skill')),
            ],
            options={
                'ordering': ['skill__skill_name', 'url'],
                'unique_together': {('skill', 'url')},
            },
        ),
    ]
