# Generated by Django 6.0.5 on 2026-09-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_rejected_resource_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
