# Generated by Django 6.0.5 on 2026-09-27 09:29

from django.db import migrations, models


def carry_the_single_department_over(apps, schema_editor):
    """Every course had one department; it becomes a list of one.

    Written out rather than left to a default, because a course with no list
    and a course that genuinely belongs to no department are the same row
    afterwards, and only this migration still knows which was which.
    """
    Course = apps.get_model("resources", "Course")
    for course in Course.objects.exclude(department="").exclude(department=None):
        course.departments = [course.department]
        course.save(update_fields=["departments"])


def put_the_first_one_back(apps, schema_editor):
    Course = apps.get_model("resources", "Course")
    for course in Course.objects.exclude(departments=[]):
        course.department = (course.departments or [""])[0]
        course.save(update_fields=["department"])


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(carry_the_single_department_over,
                             put_the_first_one_back),
        migrations.RemoveField(model_name="course", name="department"),
    ]
