"""Publish the current privacy notice as a static snapshot for the public page.

    python manage.py export_privacy_notice
    python manage.py export_privacy_notice --check

``/privacy-notice`` is the URL given to Google as the application's privacy
policy, and it has to be readable by a reviewer who has JavaScript disabled or
who arrives while the free API instance is asleep. The page therefore renders a
copy of the notice into its HTML at build time instead of waiting for
``/api/auth/privacy-notice/current/``.

That copy is a duplication, and it is unavoidable: Vercel builds ``frontend/``
alone and cannot import this module. So the duplication is made explicit rather
than hidden. The snapshot is generated from ``get_notice()`` -- never written by
hand -- and ``--check`` compares it with the canonical notice and exits non-zero
on any difference. A test runs the same comparison, so publishing a new notice
version without refreshing the public page fails the suite rather than leaving
the legal URL quietly out of date.

The backend stays canonical. The page still asks the API for the current notice
once it loads, and shows that when it arrives; the snapshot is what is on the
page before then, and what stays there if the request fails.

``contact_email`` is written into the snapshot but deliberately left out of the
comparison. accounts.privacy_notice injects it from PRIVACY_CONTACT_EMAIL at read
time because it is deployment configuration rather than agreed text, so it
differs between a workstation and production by design and comparing it would
make the check fail on the wrong machines. What *is* checked is that the
published address is a real one: the setting falls back to a placeholder on the
``.local`` domain, and printing that on a legal page would be worse than
printing nothing.
"""

import io
import json
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError

from accounts.privacy_notice import CURRENT_VERSION, get_notice

#: Where the frontend imports the snapshot from.
DEFAULT_PATH = (Path(settings.BASE_DIR).parent
                / "frontend" / "src" / "lib" / "privacyNoticeSnapshot.json")

#: Fields that are configuration rather than notice text. Present in the
#: snapshot, excluded from the drift comparison.
NOT_COMPARED = ("contact_email",)

GENERATED_BANNER = (
    "Generated by `python manage.py export_privacy_notice` from "
    "backend/accounts/privacy_notice.py. Do not edit by hand: the backend "
    "suite fails if this differs from the canonical notice.")


def usable_contact(address):
    """A real-looking address, and not the settings placeholder."""
    address = (address or "").strip()
    if not address or "@" not in address or any(c.isspace() for c in address):
        return False
    domain = address.rsplit("@", 1)[-1].lower()
    return not (domain.endswith(".local") or domain in ("localhost", "example.com"))


def comparable(notice):
    return {key: value for key, value in notice.items() if key not in NOT_COMPARED}


def render_snapshot(notice):
    """Deterministic text, so a regenerated snapshot produces no spurious diff."""
    document = {"_generated": GENERATED_BANNER, "notice": notice}
    return json.dumps(document, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


class Command(BaseCommand):
    help = ("Write the current privacy notice to the frontend's static snapshot, "
            "or check that the snapshot matches it.")

    def add_arguments(self, parser):
        parser.add_argument("--path", default=str(DEFAULT_PATH),
                            help="Snapshot file (default: the frontend's).")
        parser.add_argument(
            "--check", action="store_true", default=False,
            help=("Compare the snapshot with the canonical notice and exit "
                  "non-zero on any difference. Writes nothing."))

    def handle(self, *args, **options):
        path = Path(options["path"])
        canonical = get_notice()

        if options["check"]:
            self._check(path, canonical)
            return

        if not usable_contact(canonical["contact_email"]):
            raise CommandError(
                f"Refusing to publish {canonical['contact_email']!r} as the "
                "privacy contact on a public legal page. Set "
                "PRIVACY_CONTACT_EMAIL to the address students should write to, "
                "then run this again. Nothing was written.")

        path.parent.mkdir(parents=True, exist_ok=True)
        with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(render_snapshot(canonical))

        self.stdout.write(self.style.SUCCESS(
            f"Privacy notice {canonical['version']} "
            f"(effective {canonical['effective_date']}) written to {path}"))

    def _check(self, path, canonical):
        if not path.exists():
            raise CommandError(
                f"No privacy notice snapshot at {path}. The public page has "
                "nothing to render before the API responds. Run "
                "export_privacy_notice.")

        try:
            with io.open(path, encoding="utf-8") as handle:
                snapshot = json.load(handle).get("notice") or {}
        except (ValueError, AttributeError) as exc:
            raise CommandError(f"The snapshot at {path} is not valid: {exc}")

        problems = []

        # Named separately from the content comparison because it is the
        # failure that matters most and the easiest one to read.
        if snapshot.get("version") != canonical["version"]:
            problems.append(
                f"version: snapshot has {snapshot.get('version')!r}, the "
                f"current notice is {canonical['version']!r}")

        expected, actual = comparable(canonical), comparable(snapshot)
        for key in sorted(set(expected) | set(actual)):
            if key == "version":
                continue
            if expected.get(key) != actual.get(key):
                problems.append(f"{key}: differs from the canonical notice")

        if not usable_contact(snapshot.get("contact_email")):
            problems.append(
                f"contact_email: {snapshot.get('contact_email')!r} is not an "
                "address a reader could write to")

        if problems:
            raise CommandError(
                "The public privacy notice snapshot is out of date with "
                "accounts.privacy_notice (current version "
                f"{CURRENT_VERSION}):\n    " + "\n    ".join(problems)
                + "\n\n        Run `python manage.py export_privacy_notice` and "
                  "commit the regenerated snapshot with the notice change.")

        self.stdout.write(self.style.SUCCESS(
            f"Privacy notice snapshot matches version {canonical['version']} "
            f"(effective {canonical['effective_date']})."))
