# Generated by Django 6.0.5 on 2026-06-09 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('job_listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='source_portal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='source_type',
            field=models.CharField(choices=[('COMPANY', 'Company-posted'), ('SCRAPED', 'Scraped')], default='COMPANY', max_length=10),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='source_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='accounts.company'),
        ),
    ]
