# Generated by Django 6.0.5 on 2026-06-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0003_migrate_scraped_jobs'),
        ('scrape_jobs', '0003_jobtitle_skillalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='job_title_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_listings', to='scrape_jobs.jobtitle'),
        ),
    ]
