# Generated by Django 6.0.5 on 2026-08-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0008_joblisting_canonical_occupation'),
        ('scrape_jobs', '0007_icttrack_ictrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='ict_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_listings', to='scrape_jobs.icttrack'),
        ),
    ]
