# Generated by Django 6.0.5 on 2026-08-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0009_joblisting_ict_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobskill',
            name='required_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=20),
        ),
    ]
