# Generated by Django 6.0.5 on 2026-08-30 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0010_jobskill_required_level'),
        ('scrape_jobs', '0009_jobtitle_ict_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='ict_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_listings', to='scrape_jobs.ictrole'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='ict_role_match_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='ict_role_match_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='ict_role_name',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='ict_role_review_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('AUTO_MATCHED', 'Automatically matched'), ('VERIFIED', 'Human verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ICTRoleCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('DESCRIPTION', 'Role named in the description'), ('UNVERIFIED_BRIDGE', 'Unverified MASCO bridge'), ('AMBIGUOUS_BRIDGE', 'Ambiguous MASCO bridge')], max_length=20)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('evidence_excerpt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('reviewed_time', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_candidates', to='job_listings.joblisting')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_candidates', to='scrape_jobs.ictrole')),
            ],
            options={
                'ordering': ['status', '-confidence', 'listing_id'],
                'unique_together': {('listing', 'role_name', 'source')},
            },
        ),
    ]
