# Generated by Django 6.0.5 on 2026-08-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0011_joblisting_ict_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
