# Generated by Django 6.0.5 on 2026-08-31 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userconsent_consent_type_and_more'),
        ('job_listings', '0012_jobapplication_applicant_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cv_processing_consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_applications', to='accounts.userconsent'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='disclosure_consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disclosure_applications', to='accounts.userconsent'),
        ),
    ]
