# Generated by Django 6.0.5 on 2026-08-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0013_jobapplication_cv_processing_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
