# Generated by Django 6.0.5 on 2026-08-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0014_jobapplication_status_changed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='occupation_seniority',
            new_name='seniority',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='canonical_occupation',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='occupation_match_confidence',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='occupation_match_method',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='occupation_review_status',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='occupation_specialization',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='occupation_standardized_at',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='standardized_job_title',
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='ict_role_review_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTO_MATCHED', 'Automatically matched'), ('VERIFIED', 'Human verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
