# Generated by Django 6.0.5 on 2026-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0015_rename_occupation_seniority_joblisting_seniority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrolecandidate',
            name='source',
            field=models.CharField(choices=[('DESCRIPTION', 'Role named in the description'), ('AMBIGUOUS_TITLE', 'Title names more than one role')], max_length=20),
        ),
    ]
