# Generated by Django 6.0.5 on 2026-08-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0017_relabel_bridge_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRoleCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('AMBIGUOUS_TITLE', 'Title names more than one Market Role'), ('DESCRIPTION', 'Suggested by advert description'), ('SIMILARITY', 'Suggested by lexical similarity (review only)')], max_length=20)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('evidence_excerpt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('reviewed_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['status', '-confidence', 'listing_id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ictrolecandidate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ictrolecandidate',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='ictrolecandidate',
            name='role',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='ict_role',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='ict_role_match_confidence',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='ict_role_match_method',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='ict_role_name',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='ict_role_review_status',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='ict_track',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='seniority',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='career_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='classification_evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='classification_method',
            field=models.CharField(choices=[('EXACT_MARKET_ROLE', 'Title is the Market Role'), ('REVIEWED_TITLE_ALIAS', 'Reviewed title alias'), ('CAREER_LEVEL_NORMALIZED_ROLE', 'Market Role after career level removed'), ('CAREER_LEVEL_NORMALIZED_ALIAS', 'Reviewed alias after career level removed'), ('REVIEWED_SEGMENT_MATCH', 'Reviewed segment of a compound title'), ('JD_RESOLVED', 'Resolved from advert responsibilities'), ('AMBIGUOUS', 'Evidence names more than one Market Role'), ('UNCLASSIFIED', 'No sufficient evidence')], db_index=True, default='UNCLASSIFIED', max_length=30),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='classified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
