# Generated by Django 6.0.5 on 2026-08-31 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0018_marketrolecandidate_and_more'),
        ('scrape_jobs', '0012_marketrole_marketrolealias_remove_ictrole_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='market_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_listings', to='scrape_jobs.marketrole'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='matched_alias',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='normalized_job_title',
            field=models.CharField(blank=True, db_index=True, max_length=250),
        ),
        migrations.AddField(
            model_name='marketrolecandidate',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_candidates', to='job_listings.joblisting'),
        ),
        migrations.AddField(
            model_name='marketrolecandidate',
            name='market_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_candidates', to='scrape_jobs.marketrole'),
        ),
        migrations.DeleteModel(
            name='ICTRoleCandidate',
        ),
        migrations.AlterUniqueTogether(
            name='marketrolecandidate',
            unique_together={('listing', 'market_role', 'source')},
        ),
    ]
