# Generated by Django 6.0.5 on 2026-09-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0022_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobskill',
            name='match_method',
            field=models.CharField(blank=True, choices=[('DIRECT_CANONICAL', 'Canonical name matched'), ('ALIAS', 'Alias matched'), ('CONTEXTUAL_ALIAS', 'Alias matched, context checked'), ('MANUAL', 'Entered by hand')], db_default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='matched_text',
            field=models.CharField(blank=True, db_default='', max_length=120),
        ),
    ]
