# Generated by Django 6.0.5 on 2026-09-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0023_jobskill_match_method_jobskill_matched_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='seniority_level',
            field=models.CharField(blank=True, choices=[('CHIEF', 'Chief'), ('SENIOR', 'Senior'), ('ASSOCIATE', 'Associate'), ('JUNIOR', 'Junior'), ('ENTRY', 'Entry')], db_default='', db_index=True, max_length=12),
        ),
    ]
