# Generated by Django 6.0.5 on 2026-09-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0024_joblisting_seniority_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapelog',
            name='pages_with_results',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapelog',
            name='pagination_exhausted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapelog',
            name='stop_reason',
            field=models.CharField(choices=[('PAGINATION_EXHAUSTED', 'Pagination exhausted'), ('MAX_PAGES_REACHED', 'Stopped at --max-pages'), ('BLOCKED', 'Blocked by the source'), ('FAILED', 'Failed'), ('UNKNOWN', 'Not recorded')], default='UNKNOWN', max_length=32),
        ),
    ]
