# Generated by Django 6.0.5 on 2026-09-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0025_scrapelog_pagination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapelog',
            name='stop_reason',
            field=models.CharField(choices=[('PAGINATION_EXHAUSTED', 'Pagination exhausted'), ('MAX_PAGES_REACHED', 'Stopped at --max-pages'), ('BLOCKED', 'Blocked by the source'), ('FAILED', 'Failed'), ('INTERRUPTED', 'Stopped by the operator'), ('UNKNOWN', 'Not recorded')], default='UNKNOWN', max_length=32),
        ),
    ]
