# Generated by Django 6.0.5 on 2026-09-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0026_scrapelog_interrupted'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapelog',
            name='last_page_saved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapelog',
            name='start_page',
            field=models.IntegerField(default=1),
        ),
    ]
