# Generated by Django 6.0.5 on 2026-09-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0027_scrapelog_resume_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapelog',
            name='blocked_adverts',
            field=models.IntegerField(default=0),
        ),
    ]
