# Generated by Django 6.0.5 on 2026-09-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0028_scrapelog_blocked_adverts'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cv_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cv_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
